# Generated by Django 4.1.1 on 2022-12-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_cats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cats',
        ),
    ]
