# Generated by Django 4.1.1 on 2022-12-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_delete_cats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='team',
        ),
    ]
