# Generated by Django 4.1.1 on 2022-12-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_player_count_team_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='size',
        ),
    ]
