# Generated by Django 4.1.1 on 2022-12-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_team_name_alter_team_player_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='team1',
            new_name='team',
        ),
    ]
