# Generated by Django 4.1.1 on 2022-12-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_fixtures_team1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtures',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='fixtures',
            unique_together={('team1', 'team2')},
        ),
    ]
