# Generated by Django 4.1.1 on 2022-12-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeapp', '0002_delete_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField()),
                ('owner_email', models.CharField(max_length=100)),
            ],
        ),
    ]
