# Generated by Django 4.1.1 on 2022-12-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
